/**
 * Remote 端点身份常量：host 与 client 两个 half 的单一事实源。
 *
 * 两端点的 `<package>#<namespace>/<method>` id、命名空间、方法名与 typeSymbol
 * 只在此声明一次；host（src-json 贡献）与 client（strict+schema 贡献）据此
 * 各自组装，避免两处漂移。
 */

export const REMOTE_PACKAGE = '@hytime/dsh-companion';
export const REMOTE_SERVICE = 'travelNoteCompanion';
export const REMOTE_NAMESPACE = 'travelNoteCompanion';

/** host 注册的 SSE 事件推送路由，由 REMOTE_PACKAGE 单点推导，避免改名时两处漂移。 */
export const EVENTS_URL = `/plugins/${REMOTE_PACKAGE}/events`;

export const BUDDY_METHOD = 'buddy';
export const ASSET_METHOD = 'asset';
export const LATEST_REPLY_METHOD = 'latestReply';

export const BUDDY_ENDPOINT_ID = `${REMOTE_PACKAGE}#${REMOTE_NAMESPACE}/${BUDDY_METHOD}`;
export const ASSET_ENDPOINT_ID = `${REMOTE_PACKAGE}#${REMOTE_NAMESPACE}/${ASSET_METHOD}`;
export const LATEST_REPLY_ENDPOINT_ID = `${REMOTE_PACKAGE}#${REMOTE_NAMESPACE}/${LATEST_REPLY_METHOD}`;

export const BUDDY_RESULT_SYMBOL = `${REMOTE_PACKAGE}#${BUDDY_METHOD}:result`;
export const ASSET_FRAME_SYMBOL = `${REMOTE_PACKAGE}#${ASSET_METHOD}:frame`;
export const ASSET_RESULT_SYMBOL = `${REMOTE_PACKAGE}#${ASSET_METHOD}:result`;
export const LATEST_REPLY_RESULT_SYMBOL = `${REMOTE_PACKAGE}#${LATEST_REPLY_METHOD}:result`;

export const STATUS_METHOD = 'status';
export const STATUS_ENDPOINT_ID = `${REMOTE_PACKAGE}#${REMOTE_NAMESPACE}/${STATUS_METHOD}`;
export const STATUS_RESULT_SYMBOL = `${REMOTE_PACKAGE}#${STATUS_METHOD}:result`;

// ---- 配置页 RPC（task 3 Host @Remote 方法，task 4 Client 描述符补齐） ----

export const AUTH_STATUS_METHOD = 'authStatus';
export const LOGIN_METHOD = 'login';
export const REGISTER_METHOD = 'register';
export const LOGOUT_METHOD = 'logout';
export const GET_CONFIG_METHOD = 'getConfig';
export const SET_CONFIG_METHOD = 'setConfig';
export const LIST_SCHEDULES_METHOD = 'listSchedules';
export const ENABLE_SCHEDULE_METHOD = 'enableSchedule';
export const DISABLE_SCHEDULE_METHOD = 'disableSchedule';
export const DELETE_SCHEDULE_METHOD = 'deleteSchedule';

export const AUTH_STATUS_ENDPOINT_ID = `${REMOTE_PACKAGE}#${REMOTE_NAMESPACE}/${AUTH_STATUS_METHOD}`;
export const LOGIN_ENDPOINT_ID = `${REMOTE_PACKAGE}#${REMOTE_NAMESPACE}/${LOGIN_METHOD}`;
export const REGISTER_ENDPOINT_ID = `${REMOTE_PACKAGE}#${REMOTE_NAMESPACE}/${REGISTER_METHOD}`;
export const LOGOUT_ENDPOINT_ID = `${REMOTE_PACKAGE}#${REMOTE_NAMESPACE}/${LOGOUT_METHOD}`;
export const GET_CONFIG_ENDPOINT_ID = `${REMOTE_PACKAGE}#${REMOTE_NAMESPACE}/${GET_CONFIG_METHOD}`;
export const SET_CONFIG_ENDPOINT_ID = `${REMOTE_PACKAGE}#${REMOTE_NAMESPACE}/${SET_CONFIG_METHOD}`;
export const LIST_SCHEDULES_ENDPOINT_ID = `${REMOTE_PACKAGE}#${REMOTE_NAMESPACE}/${LIST_SCHEDULES_METHOD}`;
export const ENABLE_SCHEDULE_ENDPOINT_ID = `${REMOTE_PACKAGE}#${REMOTE_NAMESPACE}/${ENABLE_SCHEDULE_METHOD}`;
export const DISABLE_SCHEDULE_ENDPOINT_ID = `${REMOTE_PACKAGE}#${REMOTE_NAMESPACE}/${DISABLE_SCHEDULE_METHOD}`;
export const DELETE_SCHEDULE_ENDPOINT_ID = `${REMOTE_PACKAGE}#${REMOTE_NAMESPACE}/${DELETE_SCHEDULE_METHOD}`;

export const AUTH_STATUS_RESULT_SYMBOL = `${REMOTE_PACKAGE}#${AUTH_STATUS_METHOD}:result`;
export const LOGIN_RESULT_SYMBOL = `${REMOTE_PACKAGE}#${LOGIN_METHOD}:result`;
export const LOGIN_USERNAME_SYMBOL = `${REMOTE_PACKAGE}#${LOGIN_METHOD}:username`;
export const LOGIN_PASSWORD_SYMBOL = `${REMOTE_PACKAGE}#${LOGIN_METHOD}:password`;
export const REGISTER_RESULT_SYMBOL = `${REMOTE_PACKAGE}#${REGISTER_METHOD}:result`;
export const REGISTER_USERNAME_SYMBOL = `${REMOTE_PACKAGE}#${REGISTER_METHOD}:username`;
export const REGISTER_PASSWORD_SYMBOL = `${REMOTE_PACKAGE}#${REGISTER_METHOD}:password`;
export const LOGOUT_RESULT_SYMBOL = `${REMOTE_PACKAGE}#${LOGOUT_METHOD}:result`;
export const GET_CONFIG_RESULT_SYMBOL = `${REMOTE_PACKAGE}#${GET_CONFIG_METHOD}:result`;
export const SET_CONFIG_RESULT_SYMBOL = `${REMOTE_PACKAGE}#${SET_CONFIG_METHOD}:result`;
export const SET_CONFIG_PARTIAL_SYMBOL = `${REMOTE_PACKAGE}#${SET_CONFIG_METHOD}:partial`;
export const LIST_SCHEDULES_RESULT_SYMBOL = `${REMOTE_PACKAGE}#${LIST_SCHEDULES_METHOD}:result`;
export const ENABLE_SCHEDULE_RESULT_SYMBOL = `${REMOTE_PACKAGE}#${ENABLE_SCHEDULE_METHOD}:result`;
export const ENABLE_SCHEDULE_ID_SYMBOL = `${REMOTE_PACKAGE}#${ENABLE_SCHEDULE_METHOD}:id`;
export const DISABLE_SCHEDULE_RESULT_SYMBOL = `${REMOTE_PACKAGE}#${DISABLE_SCHEDULE_METHOD}:result`;
export const DISABLE_SCHEDULE_ID_SYMBOL = `${REMOTE_PACKAGE}#${DISABLE_SCHEDULE_METHOD}:id`;
export const DELETE_SCHEDULE_RESULT_SYMBOL = `${REMOTE_PACKAGE}#${DELETE_SCHEDULE_METHOD}:result`;
export const DELETE_SCHEDULE_ID_SYMBOL = `${REMOTE_PACKAGE}#${DELETE_SCHEDULE_METHOD}:id`;
